version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: local-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./runtime/mosquitto/data:/mosquitto/data
      - ./runtime/mosquitto/log:/mosquitto/log
